### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_name'

### ISSUE THREAD

**Issue by rn232** [Szwendacz99/BookStack-Python-exporter#1]
Hello,

When I try to execute the script, I have this output : 

```python
File "C:\Users\user\Desktop\BookStack-Python-exporter-main\exporter.py", line 129, in <module>
    f"using Book \"{books.get(parent_id).get_name()}\" as a parent.")
AttributeError: 'NoneType' object has no attribute 'get_name'
```

Do you know how to fix it?

Thank you!

**Comment by Szwendacz99** [comment]
Hello,

sorry for not answering for so long, but I was busy lately.
This seems like it was run on older version of BookStack, that might give different values through api. So to try find reason of the problem, I might need the version of BookStack instance on which exporter was working. 
Also I will be publishing releases with description on which BookStack version the release was tested, because small changes in api might totally break this exporter.

**Comment by Szwendacz99** [comment]
Seem to be fixed for a longer time now, closing.
